[package]
name = "rust-rpc-windows-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonrpsee = "0.15.1"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
tokio = { version = "1.16", features = ["full"] }
